### ISSUE TITLE
Make a real distributable package

### ISSUE THREAD

**Issue by temsa** [resthub/resthub-js#2]
Right now, it is pretty "hard" to get a quick resthub-js distribution working for someone just interested in the JS part of the Resthub project. 

What I had to do in order to be sure to get a "distributable" version for my students was :
- Getting the 1.1-rc4 download (available thanks to github which makes packages from branches ?)
- Do a mvn install (I guess I could avoid this, but this was just to make sure I'm not missing anything)
- Go to target/${finalname}
- Make a zip of "lib" and "test" folder (the latter in order to get some programming examples for a quick start)
- Distribute the zip and tell my students to unzip it in their webapp directory.

Most people doing JavaScript don't do it through Maven, so it would be better to provide a distributable package as well as the maven war ;)

**Comment by sdeleuze** [comment]
Duplicated with issue #15
